resource "azurerm_resource_group" "terra-RG" {
  name     = var.resourceGroupName
  location = var.location
}

resource "azapi_resource" "Terra-grafana-managed" {
  type = "Microsoft.Dashboard/grafana@2021-09-01-preview"
  name = "grafana-stan-2"
  # cf. https://docs.microsoft.com/en-us/rest/api/managed-grafana/grafana/create
  parent_id = azurerm_resource_group.terra-RG.id
  identity {
      type = "SystemAssigned"
  }
   location = var.location
  # cf. https://docs.microsoft.com/en-us/rest/api/managed-grafana/grafana/create#managedgrafanaproperties
  body = jsonencode({
    properties = {
        autoGeneratedDomainNameLabelScope = "TenantReuse"
        zoneRedundancy = "Enabled"
    }
  })

}
