name: Trigger auto deployment for hello

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Lab_6/App/**'
    - '.github/workflows/hello-AutoDeployTrigger-104505f7-19cb-4605-b1ec-346fa3c745fd.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: todelete.azurecr.io
          username: ${{ secrets.HELLO_REGISTRY_USERNAME }}
          password: ${{ secrets.HELLO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: todelete.azurecr.io/hello:${{ github.sha }}
          file: ./Lab_6/App/Dockerfile
          context: ./Lab_6/App/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HELLO_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n hello -g RG-Lab6 --server tgracrlab6.azurecr.io --username  ${{ secrets.HELLO_REGISTRY_USERNAME }} --password ${{ secrets.HELLO_REGISTRY_PASSWORD }}
            az containerapp update -n hello -g RG-Lab6 --image tgracrlab6.azurecr.io/hello:${{ github.sha }}
